name: auto-format-terraform
on: pull_request
jobs:
  format:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: formatting terraform
          title: Reformat terraform files
          body: Update terraform files to canonical format using `terraform fmt`
          branch: ${{ github.head_ref }}-automated-terraform-fmt