name: Formatter
on: pull_request
jobs:
  format:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      # MegaLinter
      - name: MegaLinter
        uses: megalinter/megalinter@v5
        env:
          APPLY_FIXES: all
          APPLY_FIXES_EVENT: push
          APPLY_FIXES_MODE: commit
          DISABLE_ERRORS: true
      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: ${{ success() }} || ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: MegaLinter reports
          path: |
            report
            mega-linter.log
          retention-days: 30 # 90 by default
      - name: Commit report
        run: |
          git config --global user.name 'Terraform format'
          git config --global user.email 'oliver-todhunter@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.OLIVERTODHUNTER_ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "Formatting"
          git push
